# Generated by Django 2.2.6 on 2019-10-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('programComplex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.ProgramComplex')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('prefix', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(blank=True)),
                ('programComplex', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.ProgramComplex')),
                ('tags', models.ManyToManyField(to='wiki.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=256)),
                ('path_file', models.CharField(blank=True, max_length=256)),
                ('dateCreate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Актуальний'), ('2', 'замінений')], default='1', max_length=1)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.Update')),
            ],
        ),
    ]
