# Generated by Django 2.2.6 on 2019-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date_income',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='update',
            name='date_install',
            field=models.DateField(auto_now=True),
        ),
    ]
