# Generated by Django 2.2.6 on 2020-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20191031_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
