# Generated by Django 2.2 on 2020-04-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_remove_update_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupdate',
            name='status',
            field=models.CharField(choices=[('1', 'Актуальний'), ('2', 'Замінений')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCreate', models.DateTimeField(auto_now=True)),
                ('dataUpdate', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wiki.Update')),
                ('tags', models.ManyToManyField(to='wiki.Tag')),
            ],
        ),
    ]
