# Generated by Django 2.2 on 2020-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20200421_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='style',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileupdate',
            name='status',
            field=models.CharField(choices=[('1', 'Актуальний'), ('2', 'замінений')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
