# Generated by Django 2.2.6 on 2020-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfsZap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField(verbose_name='номер')),
                ('program', models.CharField(blank=True, max_length=50, null=True)),
                ('date_in', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
